/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {
    @Test
    public void isPositiveNumber_true() {
        System.out.println(Utils.isAllPositiveNumber("22", "-57", "23"));
    }
}
