/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi.project;

import utils.Utils;

public class App {
    public static void main(String[] args) {
        boolean flag_Positive = Utils.isAllPositiveNumber("12" , "79");

        System.out.println(flag_Positive);
    }
}
